name: muslim
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: 
  intl: 
  flutter_native_splash: ^2.2.9
  screenshot: ^3.0.0
  image_gallery_saver: ^1.6.9
  permission_handler: ^10.2.0
  shared_preferences: 
  quran: ^1.1.8
  flutter_qiblah: ^2.1.0
  flutter_offline: ^2.1.0
  flutter_svg: 
  share_plus: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ArefRuqaa-Regular
      fonts:
        - asset: assets/fonts/ArefRuqaa-Regular.ttf

    - family: Amiri-Regular
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
    - family: Tajawal-Regular
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: TitilliumWeb-ExtraLight
      fonts:
        - asset: assets/fonts/TitilliumWeb-ExtraLight.ttf

    - family: AmiriQuran-Regular
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #AmiriQuran-Regular
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
